// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_rVdb0YO2KVol0Bt2UngjFwQusuRRZBA',
    appId: '1:723353959803:web:ef813f7b40ac06fc9ad1de',
    messagingSenderId: '723353959803',
    projectId: 'recipe-app-37765',
    authDomain: 'recipe-app-37765.firebaseapp.com',
    storageBucket: 'recipe-app-37765.appspot.com',
    measurementId: 'G-XDBSHTV60N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0KDePbPM4xpzUgclZnznWytYOhnfR4zE',
    appId: '1:723353959803:android:2387c77cb4b015839ad1de',
    messagingSenderId: '723353959803',
    projectId: 'recipe-app-37765',
    storageBucket: 'recipe-app-37765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4ILgM7apJNqDlB1l5vLpCUD0H9J4jkM',
    appId: '1:723353959803:ios:605d4330d74556b19ad1de',
    messagingSenderId: '723353959803',
    projectId: 'recipe-app-37765',
    storageBucket: 'recipe-app-37765.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
